---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -w -s
        -X main.appName=go-redfish-api-idrac-client \
        -X main.appVersion={{ .Version }} \
        -X main.gitCommit={{ .Commit }} \
        -X main.gitBranch={{ .Branch }} \
        -X main.BuildUser=greenpau \
        -X main.BuildDate={{ .Date }} \
        -gcflags="all=-trimpath=$(GOPATH)/src" \
        -asmflags="all=-trimpath $(GOPATH)/src" cmd/$(APP)/*
    main: './cmd/go-redfish-api-idrac-client'
    asmflags:
      - 'all=-trimpath={{.Env.GOPATH}}'
    gcflags:
      - 'all=-trimpath={{.Env.GOPATH}}'
    binary: go-redfish-api-idrac-client
archives:
  - name_template: "go-redfish-api-idrac-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
